//! Deterministic, seeded RNG for the logic layer.
//!
//! Survivor selection, partition scheduling and op ordering must be
//! reproducible. We use ChaCha20 seeded from an explicit `u64` so a scenario
//! seed fully determines the logical trace.
//!
//! NOTE (honesty boundary, see PHASE_0/1 findings): this RNG governs *logic*
//! only. MLS key material is generated by `openmls_rust_crypto::RustCrypto`,
//! whose internal `ChaCha20Rng` is seeded `from_entropy()` with no public
//! seeding constructor in v0.5.1. Therefore MLS *ciphertext / key bytes* are
//! NOT bit-reproducible. Reproducibility is asserted at the logical layer
//! (clock values, RNG draws, lineage structure, decrypted plaintext, member
//! sets), which is what the survivor-selection and merge-order invariants
//! actually depend on.

use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha20Rng;

/// Seeded deterministic RNG. Clone to fork an independent identical stream.
#[derive(Clone)]
pub struct DetRng {
    inner: ChaCha20Rng,
}

impl DetRng {
    pub fn from_seed(seed: u64) -> Self {
        Self {
            inner: ChaCha20Rng::seed_from_u64(seed),
        }
    }

    pub fn next_u64(&mut self) -> u64 {
        self.inner.gen()
    }

    /// Uniform index in `0..len`. Panics if `len == 0`.
    pub fn index(&mut self, len: usize) -> usize {
        assert!(len > 0, "index over empty range");
        self.inner.gen_range(0..len)
    }

    /// Deterministic Fisher–Yates shuffle (used to fuzz op/partition orderings).
    pub fn shuffle<T>(&mut self, slice: &mut [T]) {
        for i in (1..slice.len()).rev() {
            let j = self.inner.gen_range(0..=i);
            slice.swap(i, j);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn same_seed_same_stream() {
        let mut a = DetRng::from_seed(42);
        let mut b = DetRng::from_seed(42);
        for _ in 0..100 {
            assert_eq!(a.next_u64(), b.next_u64());
        }
    }

    #[test]
    fn different_seed_diverges() {
        let mut a = DetRng::from_seed(1);
        let mut b = DetRng::from_seed(2);
        assert_ne!(a.next_u64(), b.next_u64());
    }

    #[test]
    fn shuffle_is_deterministic() {
        let mut a = DetRng::from_seed(7);
        let mut b = DetRng::from_seed(7);
        let mut va: Vec<u32> = (0..10).collect();
        let mut vb = va.clone();
        a.shuffle(&mut va);
        b.shuffle(&mut vb);
        assert_eq!(va, vb);
    }
}
